/* eslint-disable import/no-anonymous-default-export */
export default {
  login: "yashar-akish",
  id: 71472986,
  node_id: "MDQ6VXNlcjcxNDcyOTg2",
  avatar_url: "https://avatars.githubusercontent.com/u/71472986?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/yashar-akish",
  html_url: "https://github.com/yashar-akish",
  followers_url: "https://api.github.com/users/yashar-akish/followers",
  following_url: "https://api.github.com/users/yashar-akish/following{/other_user}",
  gists_url: "https://api.github.com/users/yashar-akish/gists{/gist_id}",
  starred_url: "https://api.github.com/users/yashar-akish/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/yashar-akish/subscriptions",
  organizations_url: "https://api.github.com/users/yashar-akish/orgs",
  repos_url: "https://api.github.com/users/yashar-akish/repos",
  events_url: "https://api.github.com/users/yashar-akish/events{/privacy}",
  received_events_url: "https://api.github.com/users/yashar-akish/received_events",
  type: "User",
  site_admin: false,
  name: "Yashar Akish",
  company: null,
  blog: "",
  location: "Toronto Canada",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 45,
  public_gists: 0,
  followers: 0,
  following: 3,
  created_at: "2020-09-18T00:02:08Z",
  updated_at: "2021-12-27T02:24:24Z"
  };
